version: '3'
services:
  ubuntu22:
    build: ./ubuntu
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./ubuntu/data/home:/home
      - ./ubuntu/data/root:/root
    ports:
     - "2201:22"

  ubuntu-compile:
    build: ./ubuntu-compile
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./ubuntu-compile/data/home:/home
      - ./ubuntu-compile/data/root:/root
    ports:
     - "2210:22"

  ubuntu-compile-openwrt:
    build: ./ubuntu-compile-openwrt
    environment:
      TZ: Asia/Shanghai
    volumes:
      - compile-openwrt:/root # compile-openwrt 是数据卷
      - compile-openwrt-home:/home
    ports:
     - "2211:22"

volumes:
  compile-openwrt:
  compile-openwrt-home:
